### ISSUE TITLE
Network Plugin not working

### ISSUE THREAD

**Issue by Almaral-Engineering** [facebook/Sonar#161] opened 2018-07-18 18:33 UTC
I am using Volley for the requests, do I have to use okHttp? I just see an empty screen

My code:

```
 final NetworkSonarPlugin networkSonarPlugin = new NetworkSonarPlugin();
        final DescriptorMapping descriptorMapping = DescriptorMapping.withDefaults();
        if (BuildConfig.DEBUG && SonarUtils.shouldEnableSonar(this)) {
            final SonarClient client = AndroidSonarClient.getInstance(this);
            client.addPlugin(networkSonarPlugin);
            client.addPlugin(new InspectorSonarPlugin(getApplicationContext(), descriptorMapping));
            client.addPlugin(new SharedPreferencesSonarPlugin(context,
                    ConfigurationsManager.PREFS_NAME));
            client.start();
        }

```

**Comment by priteshrnandgaonkar** [comment] 2018-07-20 13:56
Duplicate of #147 , thus closing it

**Closed by priteshrnandgaonkar** 2018-07-20 13:56 UTC
