### ISSUE TITLE
Unable to build Android Project

### ISSUE THREAD

**Issue by rohfosho** [facebook/Sonar#37] opened 2018-06-12 04:18 UTC
Can't build the android project because the `fb` directory is not present.

This causes the following files to not be found:

`fb/visibility.h`
`fb/fbjni.h`
`fb/**`

**Comment by wickedev** [comment] 2018-06-12 04:59
also following files are not found
`fb/assert.h`
`fb/fbjni/ByteBuffer.h`
`fb/log.h`
`fb/Countable.h`
`fb/visibility.h`
`fb/fbjni/CoreClasses.h`

**Comment by andreiverdes** [comment] 2018-06-12 13:49
Also the `https://github.com/mozilla/rhino` lib is missing and `Console` plugin is throwing errors

**Comment by kele86838437** [comment] 2018-06-13 23:06
Fatal error: '__config' file not found when folly built

**Comment by priteshrnandgaonkar** [comment] 2018-06-25 13:32
Currently on master branch, project builds through gradle.But at runtime the sample app freezes. The issue is with `sonarfb.so` file. We are investigating the bug and any help in regards to this will be appreciated. 

Run `./gradlew :sample:installDebug` from the root directory. Make sure the emulator is up before running the previous command.

**Comment by priteshrnandgaonkar** [comment] 2018-06-25 21:53
On current master, one can build and run sonar and sample android app. Gradle builds are working,
try `./gradlew :sample:installDebug`. Closing the issue as it is fixed.

**Closed by priteshrnandgaonkar** 2018-06-25 21:53 UTC
Labels: Android
