### ISSUE TITLE
SonarKitNetworkPlugin Not work?

### ISSUE THREAD

**Issue by qokelate** [facebook/Sonar#83] opened 2018-06-19 08:40 UTC
**Add Plugin:**
```
[client addPlugin: [SonarKitNetworkPlugin new]];
```

**Test Code:**
```
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
       
        while (1)
        {
            NSMutableURLRequest *req = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"https://www.apple.com/"]];
            [[[NSURLSession sharedSession] dataTaskWithRequest:req completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
                
                
            }] resume];
            
            NSData *data1 = [NSData dataWithContentsOfURL:[NSURL URLWithString:@"https://www.apple.com/"]];
            [NSThread sleepForTimeInterval:0.5];
        }

    });
```

`Sonar.app` nothing showing ............

![temp](https://user-images.githubusercontent.com/7110985/41586486-6fedb55a-73df-11e8-9c1d-1e4fbc194be7.png)

**Comment by priteshrnandgaonkar** [comment] 2018-06-19 10:40
Are you trying it in simulator or Actual Device?

**Comment by qokelate** [comment] 2018-06-20 02:06
It's run in simulator and LayoutPlugin work well, when run in actual device, `Sonar.app` not found my device, issue here [https://github.com/facebook/Sonar/issues/76](https://github.com/facebook/Sonar/issues/76)

**Comment by priteshrnandgaonkar** [comment] 2018-06-22 10:34
We do not support the actual device for now, as the reason mentioned in #76. Closing for now as it is duplicate of #76.

**Closed by priteshrnandgaonkar** 2018-06-22 10:34 UTC
Labels: iOS
