### ISSUE TITLE
Any iOS SDK released?

### ISSUE THREAD

**Issue by qokelate** [facebook/Sonar#63] opened 2018-06-13 06:41 UTC
Pod install failed, too more errors....

**CocoaPods could not find compatible versions for pod "PeerTalk":**

Or

**CocoaPods could not find compatible versions for pod "ComponentKit":**

Or

** /xxxxx/Pods/Sonar/xplat/Sonar/SonarWebSocketImpl.cpp:102:8: No member named 'delayedUnsafe' in 'folly::Future<folly::Unit>'  **

..............

**Comment by priteshrnandgaonkar** [comment] 2018-06-13 10:47
Duplicate of #65

**Closed by priteshrnandgaonkar** 2018-06-13 10:47 UTC
